### ISSUE TITLE
cli.js not found when installing from npm or master

### ISSUE THREAD

**Issue by spacious** [nknapp/bootprint#1]
Not sure if anyone else is experiencing this- but was not able install from master or npm.

Received the following error:

npm ERR! Darwin 13.4.0
npm ERR! argv "node" "~/.node/bin/npm" "install" "-g" "bootprint" (or "./bootprint-master")
npm ERR! node v0.10.31
npm ERR! npm  v2.7.5
npm ERR! path ~/node_modules/bootprint/cli.js
npm ERR! code ENOENT
npm ERR! errno 34

Did install when using this: https://github.com/nknapp/bootprint/tree/7502e250a3706e68bd1c092c4ed6eee746bcf2f9

(where cli.js is present)

**Comment by tbzvst** [comment]
Hi,
same problem here:

npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "bootprint"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! path /usr/local/lib/node_modules/bootprint/cli.js
npm ERR! code ENOENT
npm ERR! errno -2

npm ERR! enoent ENOENT, chmod '/usr/local/lib/node_modules/bootprint/cli.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

How can I install it?

Thank You

**Comment by nknapp** [comment]
Thanks for the report. This was an accident. I did some file-renames while writing documentation for the project and appearently did not adjust the `bin'-property of `package.json`. I have published a new version with. Can you verify the fix? I can only test on Linux

```bash
npm install -g bootprint
npm install -g bootprint-swagger
bootprint swagger http://petstore.swagger.io/v2/swagger.json target
```

**Comment by tbzvst** [comment]
Yes! Now the install process is ok. Tested on Mac Os X 10.9.5.

Thank You

**Comment by spacious** [comment]
Also tested in OSX 10.9.5 Node v0.10.38 and working-

This can be closed-

Great package, thanks for your work!
