### ISSUE TITLE
YAML-support

### ISSUE THREAD

**Issue by nknapp** [nknapp/bootprint#4]
Moved here from [bootprint-swagger](https://github.com/nknapp/bootprint-swagger/issues/15).

@Otann: Is it possible to support yaml format for documentation?

It looks like now it is default format in [Swagger Editor](http://editor.swagger.io/)

**Comment by nknapp** [comment]
This could probably be done using a library like [yaml-to-json](https://www.npmjs.com/package/yaml-to-json). 
The place to include it would be [the `loadFromFileOrHttp`-function](https://github.com/nknapp/bootprint/blob/master/lib/bootprint.js#L22) in `lib/bootprint.js`.

Would you want to give it a try?

**Comment by Otann** [comment]
I've tried this package from npm, but it looks like abandoned.
The code won't run on node 0.12 and github repo is missing.

**Comment by Otann** [comment]
But I've found another one here: https://github.com/nodeca/js-yaml, I would try it first and if it works fine, I would take a chance to write you a PR.

**Comment by nknapp** [comment]
That library seems to be at least worth a try. A PR would be great.
