### ISSUE TITLE
ReferenceError: httpGet is not defined

### ISSUE THREAD

**Issue by dankelleher** [nknapp/bootprint#7]
Hi, I just ran the standard install:

    npm install -g bootprint
    npm install -g bootprint-swagger

and tested with

    bootprint swagger http://petstore.swagger.io/v2/swagger.json target

and I got:

    /usr/local/lib/node_modules/bootprint/index.js:60
        return httpGet(fileOrUrlOrData).then(function (result) {
               ^
    ReferenceError: httpGet is not defined

I fixed it by adding this to index.js

    var httpGet = require('get-promise');

Looks like it may have been missed out of the recent commit?

**Comment by nknapp** [comment]
oh thanks, this might have been introduced in the latest release (I've made larger refactorings). Try to use `bootprint@0.7.3`.
